#!/usr/bin/env bash
set -euo pipefail

# Generate ble.sh faces from ~/.config/ags/theme-colors.json.
# Output ~/.config/dotfiles/blesh-theme.sh, sourced from ~/.bashrc after ble.sh.
# ble-color-setface takes 256-colour indexes, so hex is quantised to the xterm cube.
python3 - <<'PY'
import json
import os
from pathlib import Path

home = Path(os.environ["HOME"])
colors_path = home / ".config/ags/theme-colors.json"
out_path = home / ".config/dotfiles/blesh-theme.sh"
terminal_bg = "#000000"
terminal_fg = "#dddddd"


def valid(value):
    return isinstance(value, str) and len(value) == 7 and value[0] == "#" and all(c in "0123456789abcdefABCDEF" for c in value[1:])


def read_json(path, fallback):
    try:
        value = json.loads(path.read_text())
    except (OSError, ValueError, TypeError):
        return fallback
    return value


def read_accent():
    value = read_json(colors_path, {})
    accent = value.get("accent") if isinstance(value, dict) else None
    return accent if valid(accent) else "#55adff"


def rgb(value):
    value = value.lstrip("#")
    return tuple(int(value[i:i + 2], 16) for i in (0, 2, 4))


def hexrgb(value):
    return "#%02x%02x%02x" % tuple(value)


def blend(first, second, weight):
    a, b = rgb(first), rgb(second)
    return hexrgb(tuple(round(x * weight + y * (1 - weight)) for x, y in zip(a, b)))


# xterm 16-231 cube + gray ramp: setface only accepts these indexes.
palette = []
for r in range(6):
    for g in range(6):
        for b in range(6):
            palette.append((16 + 36 * r + 6 * g + b, tuple(0 if x == 0 else 55 + 40 * x for x in (r, g, b))))
for i in range(24):
    value = 8 + i * 10
    palette.append((232 + i, (value, value, value)))


def nearest(value):
    target = rgb(value)
    return min(palette, key=lambda item: sum((a - b) ** 2 for a, b in zip(item[1], target)))[0]


accent = read_accent()
invalid = "#ff6b6b"
# mid-grey was unreadable over a dark terminal.
ghost = "#b8b8b8"
# args: accent lightened, distinct from commands
args = blend(accent, "#ffffff", 0.45)
menu_bg = blend(accent, terminal_bg, 0.18)

faces = {
    "syntax_default": (args, None, ()),
    "syntax_command": (accent, None, (1,)),
    "command_builtin": (accent, None, (1,)),
    "command_builtin_dot": (accent, None, (1,)),
    "command_alias": (accent, None, ()),
    "command_function": (accent, None, (1,)),
    "command_file": (accent, None, ()),
    "command_keyword": (accent, None, ()),
    "command_directory": (accent, None, (4,)),
    "syntax_error": (invalid, None, (1,)),
    "command_jobs": (invalid, None, ()),
    "filename_directory": (terminal_fg, None, (4,)),
    "filename_directory_sticky": (terminal_fg, None, (4,)),
    "filename_link": (terminal_fg, None, (4,)),
    "filename_orphan": (terminal_fg, None, (4,)),
    "filename_other": (terminal_fg, None, (4,)),
    "filename_setuid": (terminal_fg, None, (4,)),
    "filename_setgid": (terminal_fg, None, (4,)),
    "filename_executable": (terminal_fg, None, (4,)),
    "filename_warning": (invalid, None, (4,)),
    "filename_ls_colors": (terminal_fg, None, (4,)),
    "auto_complete": (ghost, None, ()),
    "menu_complete": (terminal_fg, menu_bg, ()),
    "menu_filter_input": (terminal_fg, menu_bg, ()),
    "region_target": (terminal_fg, menu_bg, ()),
}

lines = [
    "# generated by gen-blesh-theme.sh - do not edit",
    f"# accent={accent}",
]
for name, (foreground, background, attrs) in faces.items():
    attrs_text = ",".join([f"fg={nearest(foreground)}"] + ([f"bg={nearest(background)}"] if background else []) + (["bold"] if 1 in attrs else []) + (["underline"] if 4 in attrs else []))
    lines.append(f"ble-color-setface {name} '{attrs_text}'")

content = "\n".join(lines) + "\n"
out_path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
tmp = out_path.with_name(f"{out_path.name}.tmp.{os.getpid()}")
tmp.write_text(content)
os.chmod(tmp, 0o600)
if out_path.exists() and out_path.read_bytes() == tmp.read_bytes():
    tmp.unlink()
else:
    tmp.replace(out_path)
PY
